@baseUrl = http://localhost:3000
@contentType = application/json

### 1) Healthcheck
GET {{baseUrl}}/

### 2) Teste do banco
GET {{baseUrl}}/db

### 3) Criar usuario (CLIENTE)
# Se o email já existir, vai retornar 409
# Troque o email se precisar repetir o teste

POST {{baseUrl}}/usuarios
Content-Type: {{contentType}}

{
    "nome": "Cliente Teste",
    "email": "cliente.teste01@email.com",
    "senha": "123456"
}